# Generated by Django 4.2.3 on 2023-07-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('work_num', models.IntegerField()),
                ('work_time', models.IntegerField(default=0)),
            ],
        ),
    ]
