# Generated by Django 4.2.3 on 2023-07-10 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stove',
            old_name='num',
            new_name='sensor_id',
        ),
    ]
