# Generated by Django 4.2.3 on 2023-07-14 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_rename_num_stove_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stove',
            old_name='sensor_id',
            new_name='stoves_num',
        ),
        migrations.AlterField(
            model_name='stove',
            name='work_time',
            field=models.FloatField(),
        ),
    ]
