# Generated by Django 4.2.3 on 2023-07-14 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_rename_sensor_id_stove_stoves_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stove',
            name='work_time',
            field=models.FloatField(),
        ),
    ]
